generator:
  class: sfDoctrineGenerator
  param:
    model_class:           UserLoginLog
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user_login_log
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [nb_entries, created_at, User]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
