<?php

/**
 * PluginUserLoginLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUserLoginLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUserLoginLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUserLoginLog');
    }
}