generator:
  class: sfDoctrineGenerator
  param:
    model_class:           UserLoginHistory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user_login_history
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ip, state, User, created_at]
      filter:
        display: [user_id]
      form:    ~
      edit:    ~
      new:     ~
