UserLoginHistory:
  actAs:
    Timestampable:
      updated:
        disabled: true
  columns:
    ip: string(16)
    state: string(6)
    user_id: integer
  relations:
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      foreignAlias: LoginHistoryEntries

UserLoginLog:
  columns:
    nb_entries: integer
    created_at: date
    created_by: integer
  relations:
    User:
      class: sfGuardUser
      local: created_by
      foreign: id
      foreignAlias: LoginHistoryLog
